ARG ALPINE_VERSION=3.17

FROM alpine:${ALPINE_VERSION}
ARG USERNAME=apprunner
ARG USER_UID=1000
ARG USER_GID=1000
ARG HOMEDIR=/app
ARG SHELL=/bin/sh

RUN adduser $USERNAME -s $SHELL -D -h $HOMEDIR -u $USER_UID $USER_GID 

USER $USERNAME
WORKDIR $HOMEDIR
COPY bin/helloweb .

CMD ["./helloweb"]

